apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-flex
  labels:
    app: redis-flex
spec:
  replicas: 1
  selector:
    app: redis-flex
  template:
    metadata:
      labels:
        app: redis-flex
    spec: 
      containers:
      - name: redis-flex
        image: redis
        ports:
        - containerPort: 6379
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 60
          timeoutSeconds: 2
        volumeMounts:
        - name: redis-flex
          mountPath: /data
      volumes:
      - name: redis-flex
        flexVolume:
          driver: code/flexrex
          fsType: xfs
          options:
            volumeID: redis-flex

