apiVersion: v1
kind: Service
metadata:
  name: redis-flex
  labels:
    app: redis-flex
  annotations:
    avi_proxy: '{"virtualservice": {"auto_allocate_ip": true, "east_west_placement": false}}'
spec:
  ports:
  - port: 6379
  selector:
    app: redis-flex
