apiVersion: v1
kind: ReplicationController
metadata:
  name: graphite
  labels:
    app: graphite
spec:
  replicas: 1
  selector:
    app: graphite
  template:
    metadata:
      labels:
        app: graphite
    spec: 
      containers:
      - name: graphite
        image: cduchesne/graphite 
        ports:
        - containerPort: 80
        - containerPort: 2003
        livenessProbe:
          tcpSocket:
            port: 2003 
          initialDelaySeconds: 30
          timeoutSeconds: 3
        volumeMounts:
        - name: graphite
          mountPath: /opt/graphite/storage/whisper 
      volumes:
      - name: graphite
        libStorage:
          host: http://10.50.22.100:7979
          volumeName: graphite
          service: scaleio
